// Code generated by ent, DO NOT EDIT.

package ent

import (
	"calendar-backend/internal/storage/postgresql/ent/events"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventsCreate is the builder for creating a Events entity.
type EventsCreate struct {
	config
	mutation *EventsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ec *EventsCreate) SetName(s string) *EventsCreate {
	ec.mutation.SetName(s)
	return ec
}

// SetSexAge sets the "sex_age" field.
func (ec *EventsCreate) SetSexAge(s string) *EventsCreate {
	ec.mutation.SetSexAge(s)
	return ec
}

// SetDiscipline sets the "discipline" field.
func (ec *EventsCreate) SetDiscipline(s string) *EventsCreate {
	ec.mutation.SetDiscipline(s)
	return ec
}

// SetTimeStart sets the "time_start" field.
func (ec *EventsCreate) SetTimeStart(t time.Time) *EventsCreate {
	ec.mutation.SetTimeStart(t)
	return ec
}

// SetTimeEnd sets the "time_end" field.
func (ec *EventsCreate) SetTimeEnd(t time.Time) *EventsCreate {
	ec.mutation.SetTimeEnd(t)
	return ec
}

// SetVenue sets the "venue" field.
func (ec *EventsCreate) SetVenue(s string) *EventsCreate {
	ec.mutation.SetVenue(s)
	return ec
}

// SetParticipants sets the "participants" field.
func (ec *EventsCreate) SetParticipants(i int) *EventsCreate {
	ec.mutation.SetParticipants(i)
	return ec
}

// SetSportID sets the "sport_id" field.
func (ec *EventsCreate) SetSportID(s string) *EventsCreate {
	ec.mutation.SetSportID(s)
	return ec
}

// SetID sets the "id" field.
func (ec *EventsCreate) SetID(i int) *EventsCreate {
	ec.mutation.SetID(i)
	return ec
}

// Mutation returns the EventsMutation object of the builder.
func (ec *EventsCreate) Mutation() *EventsMutation {
	return ec.mutation
}

// Save creates the Events in the database.
func (ec *EventsCreate) Save(ctx context.Context) (*Events, error) {
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EventsCreate) SaveX(ctx context.Context) *Events {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EventsCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EventsCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EventsCreate) check() error {
	if _, ok := ec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Events.name"`)}
	}
	if _, ok := ec.mutation.SexAge(); !ok {
		return &ValidationError{Name: "sex_age", err: errors.New(`ent: missing required field "Events.sex_age"`)}
	}
	if _, ok := ec.mutation.Discipline(); !ok {
		return &ValidationError{Name: "discipline", err: errors.New(`ent: missing required field "Events.discipline"`)}
	}
	if _, ok := ec.mutation.TimeStart(); !ok {
		return &ValidationError{Name: "time_start", err: errors.New(`ent: missing required field "Events.time_start"`)}
	}
	if _, ok := ec.mutation.TimeEnd(); !ok {
		return &ValidationError{Name: "time_end", err: errors.New(`ent: missing required field "Events.time_end"`)}
	}
	if _, ok := ec.mutation.Venue(); !ok {
		return &ValidationError{Name: "venue", err: errors.New(`ent: missing required field "Events.venue"`)}
	}
	if _, ok := ec.mutation.Participants(); !ok {
		return &ValidationError{Name: "participants", err: errors.New(`ent: missing required field "Events.participants"`)}
	}
	if _, ok := ec.mutation.SportID(); !ok {
		return &ValidationError{Name: "sport_id", err: errors.New(`ent: missing required field "Events.sport_id"`)}
	}
	return nil
}

func (ec *EventsCreate) sqlSave(ctx context.Context) (*Events, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EventsCreate) createSpec() (*Events, *sqlgraph.CreateSpec) {
	var (
		_node = &Events{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(events.Table, sqlgraph.NewFieldSpec(events.FieldID, field.TypeInt))
	)
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ec.mutation.Name(); ok {
		_spec.SetField(events.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ec.mutation.SexAge(); ok {
		_spec.SetField(events.FieldSexAge, field.TypeString, value)
		_node.SexAge = value
	}
	if value, ok := ec.mutation.Discipline(); ok {
		_spec.SetField(events.FieldDiscipline, field.TypeString, value)
		_node.Discipline = value
	}
	if value, ok := ec.mutation.TimeStart(); ok {
		_spec.SetField(events.FieldTimeStart, field.TypeTime, value)
		_node.TimeStart = value
	}
	if value, ok := ec.mutation.TimeEnd(); ok {
		_spec.SetField(events.FieldTimeEnd, field.TypeTime, value)
		_node.TimeEnd = value
	}
	if value, ok := ec.mutation.Venue(); ok {
		_spec.SetField(events.FieldVenue, field.TypeString, value)
		_node.Venue = value
	}
	if value, ok := ec.mutation.Participants(); ok {
		_spec.SetField(events.FieldParticipants, field.TypeInt, value)
		_node.Participants = value
	}
	if value, ok := ec.mutation.SportID(); ok {
		_spec.SetField(events.FieldSportID, field.TypeString, value)
		_node.SportID = value
	}
	return _node, _spec
}

// EventsCreateBulk is the builder for creating many Events entities in bulk.
type EventsCreateBulk struct {
	config
	err      error
	builders []*EventsCreate
}

// Save creates the Events entities in the database.
func (ecb *EventsCreateBulk) Save(ctx context.Context) ([]*Events, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Events, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EventsCreateBulk) SaveX(ctx context.Context) []*Events {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EventsCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EventsCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
