// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Events is the predicate function for events builders.
type Events func(*sql.Selector)

// Sports is the predicate function for sports builders.
type Sports func(*sql.Selector)
