// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "sex_age", Type: field.TypeString},
		{Name: "discipline", Type: field.TypeString},
		{Name: "time_start", Type: field.TypeTime},
		{Name: "time_end", Type: field.TypeTime},
		{Name: "venue", Type: field.TypeString},
		{Name: "participants", Type: field.TypeInt},
		{Name: "sport_id", Type: field.TypeString},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
	}
	// SportsColumns holds the columns for the "sports" table.
	SportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
	}
	// SportsTable holds the schema information for the "sports" table.
	SportsTable = &schema.Table{
		Name:       "sports",
		Columns:    SportsColumns,
		PrimaryKey: []*schema.Column{SportsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		SportsTable,
	}
)

func init() {
}
